// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXBh8DOW1kYGvuVq0CZKZpj8McpuTZbFc',
    appId: '1:718624210320:web:77d33042b5e26061bfc715',
    messagingSenderId: '718624210320',
    projectId: 'child-study-5b6f8',
    authDomain: 'child-study-5b6f8.firebaseapp.com',
    storageBucket: 'child-study-5b6f8.firebasestorage.app',
    measurementId: 'G-4XZYJN72L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUJGtBU94c3yjSzoju6TP4ol5T-MeCFyQ',
    appId: '1:718624210320:android:208bea5a32ec1e5ebfc715',
    messagingSenderId: '718624210320',
    projectId: 'child-study-5b6f8',
    storageBucket: 'child-study-5b6f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMVyMvwtX-LWxk3bp6NM0z4MRSnn4t6mo',
    appId: '1:718624210320:ios:28025501b664927bbfc715',
    messagingSenderId: '718624210320',
    projectId: 'child-study-5b6f8',
    storageBucket: 'child-study-5b6f8.firebasestorage.app',
    iosBundleId: 'com.example.classProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMVyMvwtX-LWxk3bp6NM0z4MRSnn4t6mo',
    appId: '1:718624210320:ios:28025501b664927bbfc715',
    messagingSenderId: '718624210320',
    projectId: 'child-study-5b6f8',
    storageBucket: 'child-study-5b6f8.firebasestorage.app',
    iosBundleId: 'com.example.classProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXBh8DOW1kYGvuVq0CZKZpj8McpuTZbFc',
    appId: '1:718624210320:web:d8d8270c1ac07539bfc715',
    messagingSenderId: '718624210320',
    projectId: 'child-study-5b6f8',
    authDomain: 'child-study-5b6f8.firebaseapp.com',
    storageBucket: 'child-study-5b6f8.firebasestorage.app',
    measurementId: 'G-ZFP82M8KQ6',
  );
}
